[package]
authors = ["ekez ekez@withoutdoing.com"]
description = "A package for implementing pre-propose modules."
edition = "2021"
name = "cwd-pre-propose-base"
repository = "https://github.com/DA0-DA0/dao-contracts"
version = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query WASM exports
library = []

[dependencies]
cosmwasm-schema = "2.0.4"
cosmwasm-std = {version = "2.0.4"}
cw-denom = {path = "../cw-denom"}
cw-storage-plus = "2.0.0"
cw-utils = {version = "2.0.0"}
cw2 = "2.0.0"
cwd-interface = {path = "../cwd-interface"}
cwd-proposal-hooks = {path = "../cwd-proposal-hooks"}
cwd-voting = {path = "../cwd-voting"}
schemars = "0.8.15"
serde = {version = "1.0.175", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}

[dev-dependencies]
cw-multi-test = "2.0.1"
