[package]
authors = ["Sergei Sotnikov <sergei.s@p2p.org>", "Murad Karammaev <karammaev.murad@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
name = "neutron-vesting-lp-vault"
repository = "https://github.com/neutron/neutron-dao"
version = "0.1.0"

[dependencies]
cosmwasm-schema = {version = "2.0.4"}
cosmwasm-std = {version = "2.0.4"}
cwd-interface = {path = "../cwd-interface"}
cwd-macros = {path = "../cwd-macros"}
schemars = "0.8.15"
serde = {version = "1.0.175", default-features = false, features = ["derive"]}
thiserror = {version = "1.0"}
