[package]
name = "neutron-drop-security-subdao-pre-propose"
version = "0.1.0"
authors = ["Sergey Ratiashvivli <serg.s.r@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cwd-pre-propose-base = { version = "*", path = "../cwd-pre-propose-base" }
cw-utils = { version = "1.0.1" }
schemars = "0.8.8"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
cosmwasm-std = { version = "1.3.0" }
neutron-sdk = "0.10.0"
cwd-voting = { path = "../cwd-voting" }
cwd-interface = { path = "../cwd-interface" }
