[package]
name = "cwd-voting"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Types and methods for CosmWasm DAO voting."

[dependencies]
neutron-sdk = "0.10.0"
cosmwasm-schema = { version = "2.0.4" }
cosmwasm-std = { version = "2.0.4" }
schemars = "0.8.15"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "2.0.0"
cwd-interface = { path = "../cwd-interface" }
cwd-macros = { path = "../cwd-macros" }
cwd-core = { path = "../../contracts/dao/cwd-core" }
cw-denom = { path = "../cw-denom" }
cw-utils = { version = "2.0.0" }
cw-storage-plus = "2.0.0"
