[package]
name = "cw-denom"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for validation and handling of cw20 and native Cosmos SDK denominations."

[dependencies]
cosmwasm-std = "2.0.4"
schemars = "0.8.15"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "2.0.0"

[dev-dependencies]
cw20-base = "2.0.0"
cw-multi-test = "2.0.1"
